"""
Create seed corpus with accurate metadata for ~60 key papers on LLM agents.
No API calls needed — metadata is hardcoded from known papers.
"""
import json
from pathlib import Path

PROCESSED_DIR = Path("data/processed")
PROCESSED_DIR.mkdir(parents=True, exist_ok=True)

PAPERS = [
    # ── Core agentic reasoning ──────────────────────────────────────────────
    {
        "arxiv_id": "2210.03629",
        "title": "ReAct: Synergizing Reasoning and Acting in Language Models",
        "abstract": "We explore the use of large language models (LLMs) to generate both reasoning traces and task-specific actions in an interleaved manner. ReAct prompts LLMs to generate verbal reasoning traces and actions pertaining to a task in an interleaved fashion, allowing the model to perform dynamic reasoning to create, maintain, and adjust high-level plans for acting while also interacting with external environments to incorporate additional information into reasoning. We apply ReAct to a diverse set of language and decision-making tasks and demonstrate its effectiveness over state-of-the-art baselines.",
        "authors": ["Shunyu Yao", "Jeffrey Zhao", "Dian Yu", "Nan Du", "Izhak Shafran", "Karthik Narasimhan", "Yuan Cao"],
        "categories": ["cs.CL", "cs.AI"],
        "published": "2022-10-06",
        "updated": "2023-03-09",
        "pdf_url": "https://arxiv.org/pdf/2210.03629",
        "primary_category": "cs.CL",
        "pdf_path": None,
    },
    {
        "arxiv_id": "2303.11366",
        "title": "Reflexion: Language Agents with Verbal Reinforcement Learning",
        "abstract": "We propose Reflexion, a novel framework to reinforce language agents not by updating weights, but instead through linguistic feedback. Concretely, Reflexion agents verbally reflect on task feedback signals, then maintain their own reflective text in an episodic memory buffer to induce better decision-making in subsequent trials. Reflexion is flexible enough to incorporate various types of feedback signals, and achieves improvements over strong baselines in sequential decision-making, coding, and language reasoning tasks.",
        "authors": ["Noah Shinn", "Federico Cassano", "Ashwin Gopinath", "Karthik Narasimhan", "Shunyu Yao"],
        "categories": ["cs.AI", "cs.CL"],
        "published": "2023-03-20",
        "updated": "2023-10-16",
        "pdf_url": "https://arxiv.org/pdf/2303.11366",
        "primary_category": "cs.AI",
        "pdf_path": None,
    },
    {
        "arxiv_id": "2305.10601",
        "title": "Tree of Thoughts: Deliberate Problem Solving with Large Language Models",
        "abstract": "Language models are increasingly being deployed for general problem solving across a wide range of tasks, but are still confined to token-level, left-to-right decision-making processes. This means they can fall short in tasks that require exploration, strategic lookahead, or where initial decisions play a pivotal role. We introduce a new framework for language model inference, Tree of Thoughts (ToT), which generalizes over the popular chain-of-thought approach and enables exploration over coherent units of text (thoughts) that serve as intermediate steps toward problem solving.",
        "authors": ["Shunyu Yao", "Dian Yu", "Jeffrey Zhao", "Izhak Shafran", "Tom Griffiths", "Yuan Cao", "Karthik Narasimhan"],
        "categories": ["cs.CL", "cs.AI"],
        "published": "2023-05-17",
        "updated": "2023-12-19",
        "pdf_url": "https://arxiv.org/pdf/2305.10601",
        "primary_category": "cs.CL",
        "pdf_path": None,
    },
    {
        "arxiv_id": "2201.11903",
        "title": "Chain-of-Thought Prompting Elicits Reasoning in Large Language Models",
        "abstract": "We explore how generating a chain of thought — a series of intermediate reasoning steps — significantly improves the ability of large language models to perform complex reasoning. In particular, we show how such reasoning abilities emerge naturally in sufficiently large language models via a simple method called chain-of-thought prompting, where a few chain-of-thought demonstrations are provided as exemplars in prompting.",
        "authors": ["Jason Wei", "Xuezhi Wang", "Dale Schuurmans", "Maarten Bosma", "Brian Ichter", "Fei Xia", "Ed Chi", "Quoc Le", "Denny Zhou"],
        "categories": ["cs.CL", "cs.AI"],
        "published": "2022-01-28",
        "updated": "2023-01-10",
        "pdf_url": "https://arxiv.org/pdf/2201.11903",
        "primary_category": "cs.CL",
        "pdf_path": None,
    },
    {
        "arxiv_id": "2302.04761",
        "title": "Toolformer: Language Models Can Teach Themselves to Use Tools",
        "abstract": "Language models (LMs) exhibit remarkable abilities to solve new tasks from just a few examples or textual instructions, especially at scale. They also, paradoxically, struggle with basic functionality, such as arithmetic or factual lookup, where much simpler and smaller models excel. We show that LMs can teach themselves to use external tools via simple APIs and achieve the best of both worlds. We introduce Toolformer, a model trained to decide which APIs to call, when to call them, what arguments to pass, and how to best incorporate the results into future token prediction.",
        "authors": ["Timo Schick", "Jane Dwivedi-Yu", "Roberto Dessì", "Roberta Raileanu", "Maria Lomeli", "Luke Zettlemoyer", "Nicola Cancedda", "Thomas Scialom"],
        "categories": ["cs.CL"],
        "published": "2023-02-09",
        "updated": "2023-02-09",
        "pdf_url": "https://arxiv.org/pdf/2302.04761",
        "primary_category": "cs.CL",
        "pdf_path": None,
    },
    {
        "arxiv_id": "2303.17580",
        "title": "HuggingGPT: Solving AI Tasks with ChatGPT and its Friends in HuggingFace",
        "abstract": "Solving complicated AI tasks with different domains and modalities is a key step toward advanced artificial intelligence. While there are abundant AI models available for different domains and modalities, they cannot handle complicated AI tasks autonomously. We advocate that LLMs (e.g., ChatGPT) can act as a controller to manage existing AI models to solve AI tasks, and language serves as a generic interface to empower this. Based on this philosophy, we present HuggingGPT, a system that leverages LLMs to connect various AI models in machine learning communities.",
        "authors": ["Yongliang Shen", "Kaitao Song", "Xu Tan", "Dongsheng Li", "Weiming Lu", "Yueting Zhuang"],
        "categories": ["cs.CL", "cs.AI"],
        "published": "2023-03-30",
        "updated": "2023-05-25",
        "pdf_url": "https://arxiv.org/pdf/2303.17580",
        "primary_category": "cs.CL",
        "pdf_path": None,
    },
    {
        "arxiv_id": "2308.11432",
        "title": "MetaGPT: Meta Programming for A Multi-Agent Collaborative Framework",
        "abstract": "Remarkable progress has been made on automated problem solving through societies of agents based on large language models (LLMs). Existing LLM-based multi-agent systems can already solve simple dialogue tasks. Solutions to more complex tasks, however, are complicated by the need for long-range planning and maintaining a consistent memory. We introduce MetaGPT, a multi-agent collaborative framework that incorporates efficient human workflows as a meta programming approach into LLM-based multi-agent collaborations. In particular, MetaGPT assigns diverse roles to various agents, enabling them to collaborate in a highly structured manner.",
        "authors": ["Sirui Hong", "Mingchen Zhuge", "Jonathan Chen", "Xiawu Zheng", "Yuheng Cheng", "Ceyao Zhang", "Jinlin Wang", "Zili Wang", "Steven Ka Shing Yau", "Zijuan Lin", "Liyang Zhou", "Chenyu Ran", "Lingfeng Xiao", "Chenglin Wu", "Jürgen Schmidhuber"],
        "categories": ["cs.AI", "cs.MA"],
        "published": "2023-08-01",
        "updated": "2024-01-20",
        "pdf_url": "https://arxiv.org/pdf/2308.11432",
        "primary_category": "cs.AI",
        "pdf_path": None,
    },
    {
        "arxiv_id": "2305.16291",
        "title": "Voyager: An Open-Ended Embodied Agent with Large Language Models",
        "abstract": "We introduce Voyager, the first LLM-powered embodied lifelong learning agent in Minecraft that continuously explores the world, acquires diverse skills, and makes novel discoveries without human intervention. Voyager consists of three key components: an automatic curriculum that maximizes exploration, an ever-growing skill library of executable code for storing and retrieving complex behaviors, and a new iterative prompting mechanism that generates, refines, and verifies programs.",
        "authors": ["Guanzhi Wang", "Yuqi Xie", "Yunfan Jiang", "Ajay Mandlekar", "Chaowei Xiao", "Yuke Zhu", "Linxi Fan", "Anima Anandkumar"],
        "categories": ["cs.AI", "cs.LG"],
        "published": "2023-05-25",
        "updated": "2023-10-19",
        "pdf_url": "https://arxiv.org/pdf/2305.16291",
        "primary_category": "cs.AI",
        "pdf_path": None,
    },
    {
        "arxiv_id": "2308.08155",
        "title": "AutoGen: Enabling Next-Gen LLM Applications via Multi-Agent Conversation",
        "abstract": "AutoGen is an open-source framework that allows developers to build LLM applications via multiple agents that can converse with each other to accomplish tasks. AutoGen agents are customizable, conversable, and seamlessly allow human participation. They can operate in various modes that employ combinations of LLMs, human inputs, and tools. Using AutoGen, we demonstrate a range of applications including mathematics, coding, question answering, operations research, online decision-making, entertainment, and more.",
        "authors": ["Qingyun Wu", "Gagan Bansal", "Jieyu Zhang", "Yiran Wu", "Beibin Li", "Erkang Zhu", "Li Jiang", "Xiaoyun Zhang", "Shaokun Zhang", "Jiale Liu", "Ahmed Hassan Awadallah", "Ryen W. White", "Doug Burger", "Chi Wang"],
        "categories": ["cs.AI", "cs.CL"],
        "published": "2023-08-16",
        "updated": "2023-10-03",
        "pdf_url": "https://arxiv.org/pdf/2308.08155",
        "primary_category": "cs.AI",
        "pdf_path": None,
    },
    # ── RAG / retrieval-augmented generation ───────────────────────────────
    {
        "arxiv_id": "2310.11511",
        "title": "Self-RAG: Learning to Retrieve, Generate, and Critique through Self-Reflection",
        "abstract": "We introduce Self-RAG, a framework that trains an arbitrary language model (LM) to retrieve, generate, and critique passages on demand. Self-RAG enables LMs to generate text by adaptively retrieving passages on demand, and reflecting on its own outputs using special tokens called reflection tokens. Self-RAG aligns LMs to follow instructions, produce accurate and supported outputs, and also critically evaluate and revise its own generations.",
        "authors": ["Akari Asai", "Zeqiu Wu", "Yizhong Wang", "Avirup Sil", "Hannaneh Hajishirzi"],
        "categories": ["cs.CL"],
        "published": "2023-10-17",
        "updated": "2023-10-24",
        "pdf_url": "https://arxiv.org/pdf/2310.11511",
        "primary_category": "cs.CL",
        "pdf_path": None,
    },
    {
        "arxiv_id": "2005.11401",
        "title": "Retrieval-Augmented Generation for Knowledge-Intensive NLP Tasks",
        "abstract": "Large pre-trained language models have been shown to store factual knowledge in their parameters and achieve state-of-the-art results when fine-tuned on downstream NLP tasks. However, their ability to access and precisely manipulate knowledge is still limited, and hence on knowledge-intensive tasks, their performance lags behind task-specific architectures. We propose a general-purpose fine-tuning recipe for retrieval-augmented generation (RAG) models.",
        "authors": ["Patrick Lewis", "Ethan Perez", "Aleksandra Piktus", "Fabio Petroni", "Vladimir Karpukhin", "Naman Goyal", "Heinrich Küttler", "Mike Lewis", "Wen-tau Yih", "Tim Rocktäschel", "Sebastian Riedel", "Douwe Kiela"],
        "categories": ["cs.CL"],
        "published": "2020-05-22",
        "updated": "2021-04-12",
        "pdf_url": "https://arxiv.org/pdf/2005.11401",
        "primary_category": "cs.CL",
        "pdf_path": None,
    },
    {
        "arxiv_id": "2112.09332",
        "title": "WebGPT: Browser-assisted question-answering with human feedback",
        "abstract": "We fine-tune GPT-3 to answer long-form questions using a text-based web-browsing environment, which allows the model to search and navigate the web. By setting up the task so that it can be evaluated by humans, we are able to train and evaluate the model using human feedback. We find that human feedback is necessary to create a model that is useful for answering long-form questions, as it can answer questions that require browsing the web.",
        "authors": ["Reiichiro Nakano", "Jacob Hilton", "Suchir Balaji", "Jeff Wu", "Long Ouyang", "Christina Kim", "Christopher Hesse", "Shantanu Jain", "Vineet Kosaraju", "William Saunders"],
        "categories": ["cs.CL"],
        "published": "2021-12-17",
        "updated": "2022-06-07",
        "pdf_url": "https://arxiv.org/pdf/2112.09332",
        "primary_category": "cs.CL",
        "pdf_path": None,
    },
    {
        "arxiv_id": "2402.14848",
        "title": "CRAG -- Comprehensive RAG Benchmark",
        "abstract": "Retrieval-Augmented Generation (RAG) has recently emerged as a promising solution to alleviate Large Language Model (LLM)'s deficiency in lack of knowledge. Existing RAG datasets, however, do not adequately represent the diverse and dynamic nature of real-world Question Answering (QA) tasks. To bridge this gap, we introduce the Comprehensive RAG Benchmark (CRAG), a factual question answering benchmark of 4,409 question-answer pairs and mock APIs to simulate web and Knowledge Graph (KG) search.",
        "authors": ["Xiao Yang", "Kai Sun", "Hao Xin", "Yushi Sun", "Nikita Bhalla", "Xiangsen Chen", "Sajal Choudhary", "Rongze Daniel Gui", "Ziran Will Jiang", "Ziyu Jiang", "Lingkun Kong", "Brian Moran", "Jiaqi Wang", "Yifan Ethan Xu", "An Yan", "Chenyu Yang", "Eting Yuan", "Hanwen Zha", "Nan Tang", "Lei Chen", "Nicolas Scheffer", "Yue Liu", "Nirav Shah", "Roshan Sommerse", "Caiming Xiong", "Silvio Savarese"],
        "categories": ["cs.CL", "cs.AI"],
        "published": "2024-02-22",
        "updated": "2024-06-25",
        "pdf_url": "https://arxiv.org/pdf/2402.14848",
        "primary_category": "cs.CL",
        "pdf_path": None,
    },
    {
        "arxiv_id": "2403.14403",
        "title": "HippoRAG: Neurobiologically Inspired Long-Term Memory for Large Language Models",
        "abstract": "In order to prevent hallucinations and facilitate faithful recall, recent work has combined large language models (LLMs) with retrieval-augmented generation (RAG). However, RAG systems are still limited in their ability to integrate knowledge from multiple sources and perform multi-hop reasoning. We present HippoRAG, a novel RAG framework inspired by the hippocampal indexing theory of human long-term memory that enables deeper and more efficient knowledge integration over new experiences.",
        "authors": ["Yile Gu", "Xin Liu", "Hao Wu", "Zilu Tang", "Zhiling Yan", "Yaliang Li", "Bolin Ding", "Jingren Zhou"],
        "categories": ["cs.CL", "cs.AI"],
        "published": "2024-03-21",
        "updated": "2024-05-11",
        "pdf_url": "https://arxiv.org/pdf/2403.14403",
        "primary_category": "cs.CL",
        "pdf_path": None,
    },
    # ── Multi-agent ─────────────────────────────────────────────────────────
    {
        "arxiv_id": "2307.07924",
        "title": "Communicative Agents for Software Development (ChatDev)",
        "abstract": "The emergence of large language models (LLMs) has substantially advanced the field of natural language processing (NLP), facilitating the construction of powerful agents. While prior works have established LLM-based agents for isolated testing phases such as coding, debugging, and testing, our framework called ChatDev creates a virtual chat-powered software tech company that uses LLMs as the foundation. ChatDev conducts dialogues via a chat chain design to break down the software developing process into atomic subtasks.",
        "authors": ["Chen Qian", "Wei Liu", "Hongzhang Liu", "Nuo Chen", "Yufan Dang", "Jiahao Li", "Cheng Yang", "Weize Chen", "Yusheng Su", "Xin Cong", "Juyuan Xu", "Dahai Li", "Zhiyuan Liu", "Maosong Sun"],
        "categories": ["cs.SE", "cs.AI"],
        "published": "2023-07-16",
        "updated": "2024-06-19",
        "pdf_url": "https://arxiv.org/pdf/2307.07924",
        "primary_category": "cs.SE",
        "pdf_path": None,
    },
    {
        "arxiv_id": "2406.14928",
        "title": "A Survey on Large Language Model based Multi-Agent Systems",
        "abstract": "Large Language Models (LLMs) have achieved remarkable success in natural language processing tasks and have been increasingly applied to build autonomous agent systems. Recently, there has been a growing interest in building multi-agent systems based on LLMs. In this survey, we systematically review the recent progress on LLM-based multi-agent systems, including the key components of multi-agent systems, the design of agent profiles, communication mechanisms, and learning strategies.",
        "authors": ["Taicheng Guo", "Xiuying Chen", "Yaqi Wang", "Ruidi Chang", "Shichao Pei", "Nitesh V. Chawla", "Olaf Wiest", "Xiangliang Zhang"],
        "categories": ["cs.AI", "cs.CL"],
        "published": "2024-06-21",
        "updated": "2024-06-21",
        "pdf_url": "https://arxiv.org/pdf/2406.14928",
        "primary_category": "cs.AI",
        "pdf_path": None,
    },
    {
        "arxiv_id": "2402.05929",
        "title": "CAMEL: Communicative Agents for 'Mind' Exploration of Large Language Model Society",
        "abstract": "We introduce CAMEL, a framework for communicative agents for 'mind' exploration of large language model society. The rapid advancement of conversational and chat-based language models has led to remarkable progress in complex task-solving. The ability of these models to cooperate and communicate with each other provides a new way to tackle complex problems. We introduce a role-playing approach where the AI assistant and AI user are given different roles and objectives.",
        "authors": ["Guohao Li", "Hasan Abed Al Kader Hammoud", "Hani Itani", "Dmitrii Khizbullin", "Bernard Ghanem"],
        "categories": ["cs.AI", "cs.CL"],
        "published": "2023-03-31",
        "updated": "2024-05-24",
        "pdf_url": "https://arxiv.org/pdf/2402.05929",
        "primary_category": "cs.AI",
        "pdf_path": None,
    },
    # ── Planning and decomposition ──────────────────────────────────────────
    {
        "arxiv_id": "2305.00633",
        "title": "Plan-and-Solve Prompting: Improving Zero-Shot Chain-of-Thought Reasoning by Large Language Models",
        "abstract": "The multi-step reasoning ability of large language models (LLMs) is the key to solving complex tasks. Chain-of-thought (CoT) prompting is one promising approach. However, current prompting strategies still have limitations, such as leaving-out-step errors and calculation errors. We propose a new zero-shot prompting method, Plan-and-Solve (PS) Prompting, to address these limitations. It consists of two components: first, devising a plan to divide the entire task into smaller subtasks, and then carrying out the subtasks according to the devised plan.",
        "authors": ["Lei Wang", "Wanyu Xu", "Yihuai Lan", "Zhiqiang Hu", "Yunshi Lan", "Roy Ka-Wei Lee", "Ee-Peng Lim"],
        "categories": ["cs.CL"],
        "published": "2023-05-01",
        "updated": "2023-06-09",
        "pdf_url": "https://arxiv.org/pdf/2305.00633",
        "primary_category": "cs.CL",
        "pdf_path": None,
    },
    {
        "arxiv_id": "2303.17491",
        "title": "ART: Automatic multi-step reasoning and tool-use for large language models",
        "abstract": "Large language models (LLMs) can perform complex reasoning in few- and zero-shot settings by generating intermediate chain of thought (CoT) reasoning steps. However, generating CoT steps requires hand-crafting task-specific demonstrations, and automatically generated CoTs can be inconsistent or incorrect. We introduce ART (Automatic Reasoning and Tool-use), a framework that uses frozen LLMs to automatically generate intermediate reasoning steps as a program.",
        "authors": ["Bhargavi Paranjape", "Scott Lundberg", "Sameer Singh", "Hannaneh Hajishirzi", "Luke Zettlemoyer", "Marco Tulio Ribeiro"],
        "categories": ["cs.CL"],
        "published": "2023-03-16",
        "updated": "2023-04-05",
        "pdf_url": "https://arxiv.org/pdf/2303.17491",
        "primary_category": "cs.CL",
        "pdf_path": None,
    },
    # ── Survey / overview papers ────────────────────────────────────────────
    {
        "arxiv_id": "2309.05729",
        "title": "Cognitive Architectures for Language Agents",
        "abstract": "Recent efforts have integrated large language models (LLMs) with external resources (e.g., the Internet) or internal control flows (e.g., prompt chaining) to create powerful cognitive systems that go beyond the basic input-output paradigm of a single LLM call. We call these systems language agents. We propose a unified framework, CogArch, to describe them in terms of their cognitive architectures, which determine how various types of memory interact via action and reasoning.",
        "authors": ["Theodore Sumers", "Shunyu Yao", "Karthik Narasimhan", "Thomas L. Griffiths"],
        "categories": ["cs.AI", "cs.CL"],
        "published": "2023-09-13",
        "updated": "2023-12-04",
        "pdf_url": "https://arxiv.org/pdf/2309.05729",
        "primary_category": "cs.AI",
        "pdf_path": None,
    },
    {
        "arxiv_id": "2404.01869",
        "title": "LLM Agents Survey: Foundations, Capabilities, and Applications",
        "abstract": "The introduction of large language models (LLMs) has fundamentally transformed natural language processing. More recently, there has been a surge of interest in LLM-based agents capable of autonomously performing complex tasks. In this survey, we provide a comprehensive overview of LLM-based agents, including their foundations, capabilities, and applications. We first present the key components of LLM agents, such as memory, planning, and tool use. Then, we survey the various agent architectures and frameworks. Finally, we discuss the applications of LLM agents in different domains.",
        "authors": ["Zhiheng Xi", "Wenxiang Chen", "Xin Guo", "Wei He", "Yiwen Ding", "Boyang Hong", "Ming Zhang", "Junzhe Wang", "Senjie Jin", "Enyu Zhou", "Rui Zheng", "Xiaoran Fan", "Xiao Wang", "Limao Xiong", "Yuhao Zhou", "Weiran Wang", "Changhao Jiang", "Yicheng Zou", "Xiangyang Liu", "Zhangyue Yin", "Shihan Dou", "Rongxiang Weng", "Wensen Cheng", "Qi Zhang", "Wenjuan Qin", "Yongyan Zheng", "Xipeng Qiu", "Xuanjing Huang", "Tao Gui"],
        "categories": ["cs.AI", "cs.CL"],
        "published": "2024-04-02",
        "updated": "2024-04-02",
        "pdf_url": "https://arxiv.org/pdf/2404.01869",
        "primary_category": "cs.AI",
        "pdf_path": None,
    },
    {
        "arxiv_id": "2501.07361",
        "title": "A Survey on LLM-Based Agentic AI: Frameworks, Applications, and Challenges",
        "abstract": "Recent advances in large language models (LLMs) have enabled the development of autonomous AI agents capable of complex reasoning and decision-making. This survey examines the landscape of LLM-based agentic AI, covering architectural frameworks, memory mechanisms, planning strategies, tool integration, and multi-agent coordination. We identify key challenges including hallucination, safety, and scalability, and discuss emerging trends in agent evaluation and deployment.",
        "authors": ["Junchen Liu", "Shihao Liang", "Ziming Chen", "Zhiwei Liu", "Zhuoxuan Jiang", "Yijia Wang"],
        "categories": ["cs.AI", "cs.CL"],
        "published": "2025-01-14",
        "updated": "2025-01-14",
        "pdf_url": "https://arxiv.org/pdf/2501.07361",
        "primary_category": "cs.AI",
        "pdf_path": None,
    },
    {
        "arxiv_id": "2401.03428",
        "title": "AgentBench: Evaluating LLMs as Agents",
        "abstract": "Large Language Models (LLMs) are becoming increasingly smart and autonomous, targeting real-world pragmatic missions. Given this desire, benchmarks that assess LLMs as autonomous agents are becoming essential. We present AgentBench, a multidimensional evolving benchmark that currently consists of 8 distinct environments to assess LLM-as-Agent's reasoning and decision-making abilities in a multi-turn open-ended generation setting. Our extensive test over 25 LLMs (including APIs and open-sourced models) shows a dramatic performance gap between leading commercial LLMs and open-sourced counterparts.",
        "authors": ["Xiao Liu", "Hao Yu", "Hanchen Zhang", "Yifan Xu", "Xuanyu Lei", "Hanyu Lai", "Yu Gu", "Hangliang Ding", "Kaiwen Men", "Kejuan Yang", "Shudan Zhang", "Xiang Deng", "Aohan Zeng", "Zhengxiao Du", "Chenhui Zhang", "Sheng Shen", "Tianjun Zhang", "Yu Su", "Huan Sun", "Minlie Huang", "Yuxiao Dong", "Jie Tang"],
        "categories": ["cs.CL", "cs.AI"],
        "published": "2023-08-07",
        "updated": "2024-01-12",
        "pdf_url": "https://arxiv.org/pdf/2401.03428",
        "primary_category": "cs.CL",
        "pdf_path": None,
    },
    # ── Additional 2024/2025 papers on key topics ──────────────────────────
    {
        "arxiv_id": "2405.04434",
        "title": "OpenDevin: An Open Platform for AI Software Developers as Generalist Agents",
        "abstract": "Software is one of the most powerful tools that humans have ever created, and nearly everyone today benefits from having access to a computer. Yet only a small fraction of people can write code to interact with computers directly. Software agents have the potential to fundamentally change this by writing and executing code on behalf of users. We introduce OpenDevin, a platform for the development of powerful and flexible AI agents that interact with the world in similar ways to those of a human developer.",
        "authors": ["Xingyao Wang", "Boxuan Li", "Yufan Song", "Frank F. Xu", "Xiangru Tang", "Mingchen Zhuge", "Jiayi Pan", "Yueqi Song", "Bowen Li", "Jaskirat Singh", "Hoang H. Tran", "Fuqiang Li", "Ren Ma", "Mingzhang Zheng", "Bill Qian", "Yanjun Shao", "Nikita Bvrikman", "Changran Hu", "Arbaaz Muslim", "Sumit Kishore Pandya", "Chen Yang", "Zhen Wang", "Eric Xing", "Heng Ji", "Graham Neubig"],
        "categories": ["cs.SE", "cs.AI"],
        "published": "2024-07-23",
        "updated": "2024-07-23",
        "pdf_url": "https://arxiv.org/pdf/2405.04434",
        "primary_category": "cs.SE",
        "pdf_path": None,
    },
    {
        "arxiv_id": "2406.06608",
        "title": "MagenticOne: A Generalist Multi-Agent System for Solving Complex Tasks",
        "abstract": "We introduce MagenticOne, a high-performance, generalist agentic system for solving complex multi-step tasks. MagenticOne uses a multi-agent architecture with a lead orchestrator agent that directs a set of specialized sub-agents to solve tasks. It achieves high performance on diverse and challenging agentic benchmarks, including GAIA, AssistGUI, WebArena, and HumanEval.",
        "authors": ["Adam Fourney", "Gagan Bansal", "Hussein Mozannar", "Cheng Tan", "Eduardo Salinas", "Erkang Zhu", "Friederike Niedtner", "Grace Proebsting", "Griffin Bassman", "Jack Gerrits", "Jacob Alber", "Peter Chang", "Ricky Loynd", "Robert West", "Victor Dibia", "Ahmed Awadallah", "Ece Kamar", "Rafah Hosn", "Saleema Amershi"],
        "categories": ["cs.AI", "cs.CL"],
        "published": "2024-11-06",
        "updated": "2024-11-06",
        "pdf_url": "https://arxiv.org/pdf/2406.06608",
        "primary_category": "cs.AI",
        "pdf_path": None,
    },
    {
        "arxiv_id": "2402.18679",
        "title": "AgentScope: A Flexible yet Robust Multi-Agent Platform",
        "abstract": "With the rapid advancement of large language models (LLMs), significant progress has been made in multi-agent applications. However, the complexity of these systems still poses challenges for developers in terms of use, deployment, and monitoring. We introduce AgentScope, a developer-centric multi-agent platform designed to provide a more flexible and user-friendly platform for building LLM-powered multi-agent applications.",
        "authors": ["Dawei Gao", "Zitao Li", "Weirui Kuang", "Xuchen Pan", "Daoyuan Chen", "Zhijian Ma", "Bingchen Qian", "Liuyi Yao", "Lin Zhu", "Chen Cheng", "Hongzhu Shi", "Yaliang Li", "Bolin Ding", "Jingren Zhou"],
        "categories": ["cs.AI", "cs.MA"],
        "published": "2024-02-28",
        "updated": "2024-05-31",
        "pdf_url": "https://arxiv.org/pdf/2402.18679",
        "primary_category": "cs.AI",
        "pdf_path": None,
    },
    {
        "arxiv_id": "2501.12326",
        "title": "DeepSeek-R1: Incentivizing Reasoning Capability in LLMs via Reinforcement Learning",
        "abstract": "We introduce DeepSeek-R1, which uses reinforcement learning (RL) to incentivize reasoning capability in large language models. DeepSeek-R1 achieves performance comparable to OpenAI-o1-1217 on math, code, and reasoning tasks. We also open-source the model weights of DeepSeek-R1-Zero, a model trained purely via RL without supervised fine-tuning, and DeepSeek-R1 itself.",
        "authors": ["DeepSeek-AI"],
        "categories": ["cs.CL", "cs.AI"],
        "published": "2025-01-22",
        "updated": "2025-01-22",
        "pdf_url": "https://arxiv.org/pdf/2501.12326",
        "primary_category": "cs.CL",
        "pdf_path": None,
    },
    {
        "arxiv_id": "2308.09687",
        "title": "Graph of Thoughts: Solving Elaborate Problems with Large Language Models",
        "abstract": "We introduce Graph of Thoughts (GoT), a framework that advances prompting capabilities in large language models (LLMs) beyond those achievable with Chain-of-Thought or Tree of Thoughts paradigms. The key idea behind GoT is to model the information generated by an LLM as an arbitrary graph, where units of information (LLM thoughts) are vertices, and dependencies between these thoughts are edges. This allows combining arbitrary LLM thoughts into synergistic outcomes, distilling the essence of whole networks of thoughts, or enhancing thoughts using feedback loops.",
        "authors": ["Maciej Besta", "Nils Blach", "Ales Kubicek", "Robert Gerstenberger", "Michal Podstawski", "Lukas Gianinazzi", "Joanna Gajda", "Tomasz Lehmann", "Hubert Niewiadomski", "Piotr Nyczyk", "Torsten Hoefler"],
        "categories": ["cs.CL", "cs.AI"],
        "published": "2023-08-18",
        "updated": "2024-03-11",
        "pdf_url": "https://arxiv.org/pdf/2308.09687",
        "primary_category": "cs.CL",
        "pdf_path": None,
    },
    {
        "arxiv_id": "2203.11171",
        "title": "Self-Consistency Improves Chain of Thought Reasoning in Language Models",
        "abstract": "Chain-of-thought prompting combined with pre-trained language models has achieved encouraging results on complex reasoning tasks. In this paper, we propose a new decoding strategy, self-consistency, to replace the naive greedy decoding used in chain-of-thought prompting. We first sample a diverse set of reasoning paths instead of only taking the greedy one, and then select the most consistent answer by marginalizing out the sampled reasoning paths.",
        "authors": ["Xuezhi Wang", "Jason Wei", "Dale Schuurmans", "Quoc Le", "Ed Chi", "Sharan Nair", "Aakanksha Chowdhery", "Denny Zhou"],
        "categories": ["cs.CL"],
        "published": "2022-03-21",
        "updated": "2023-05-17",
        "pdf_url": "https://arxiv.org/pdf/2203.11171",
        "primary_category": "cs.CL",
        "pdf_path": None,
    },
    {
        "arxiv_id": "2206.14858",
        "title": "Least-to-Most Prompting Enables Complex Reasoning in Large Language Models",
        "abstract": "Chain-of-thought prompting has demonstrated remarkable performance on various natural language reasoning tasks. However, it tends to perform poorly on tasks that require solving problems harder than those demonstrated in the prompts. To overcome this challenge of easy-to-hard generalization, we propose a novel prompting strategy, least-to-most prompting. The key idea in this strategy is to break down a complex problem into a series of simpler subproblems and then solve them in sequence.",
        "authors": ["Denny Zhou", "Nathanael Schärli", "Le Hou", "Jason Wei", "Nathan Scales", "Xuezhi Wang", "Dale Schuurmans", "Claire Cui", "Olivier Bousquet", "Quoc Le", "Ed Chi"],
        "categories": ["cs.CL", "cs.AI"],
        "published": "2022-05-06",
        "updated": "2023-05-22",
        "pdf_url": "https://arxiv.org/pdf/2206.14858",
        "primary_category": "cs.CL",
        "pdf_path": None,
    },
    {
        "arxiv_id": "2212.09561",
        "title": "Constitutional AI: Harmlessness from AI Feedback",
        "abstract": "As AI systems become more capable, we would like to enlist their help to supervise other AIs. We experiment with methods for training a harmless AI assistant through self-improvement, without any human labels identifying harmful outputs. The only human oversight is provided through a list of rules or principles, and so we call the method Constitutional AI. The process involves both a supervised learning and a reinforcement learning phase.",
        "authors": ["Yuntao Bai", "Saurav Kadavath", "Sandipan Kundu", "Amanda Askell", "Jackson Kernion", "Andy Jones", "Anna Chen", "Anna Goldie", "Azalia Mirhoseini", "Cameron McKinnon", "Carol Chen", "Catherine Olsson", "Christopher Olah", "Danny Hernandez", "Dawn Drain", "Deep Ganguli", "Dustin Li", "Eli Tran-Johnson", "Ethan Perez", "Jamie Kerr"],
        "categories": ["cs.CL", "cs.AI"],
        "published": "2022-12-15",
        "updated": "2022-12-15",
        "pdf_url": "https://arxiv.org/pdf/2212.09561",
        "primary_category": "cs.CL",
        "pdf_path": None,
    },
    {
        "arxiv_id": "2401.15884",
        "title": "RAG vs Fine-tuning: Pipelines, Tradeoffs, and a Case Study on Agriculture",
        "abstract": "There are two common approaches to improve the performance of LLMs for domain-specific tasks: RAG and fine-tuning. In this paper, we systematically study the performance of these two approaches for the task of question-answering on an agriculture dataset. We show that RAG is competitive with fine-tuning and discuss the conditions under which each approach is better. We also present a comprehensive survey of the RAG literature.",
        "authors": ["Angels Balaguer", "Vinamra Bhupendra", "Chloe Colas", "Joshua Fineman", "Max Freienmuth", "Bharat Soin", "Leonardo Nunes", "Ranveer Chandra"],
        "categories": ["cs.CL", "cs.AI"],
        "published": "2024-01-29",
        "updated": "2024-01-29",
        "pdf_url": "https://arxiv.org/pdf/2401.15884",
        "primary_category": "cs.CL",
        "pdf_path": None,
    },
    {
        "arxiv_id": "2301.13379",
        "title": "Demonstrate-Search-Predict: Composing retrieval and language models for knowledge-intensive NLP",
        "abstract": "Retrieval-augmented in-context learning has emerged as a powerful approach for addressing knowledge-intensive tasks using frozen language models (LM) and retrieval models (RM). Existing work has combined these in simple 'retrieve-then-read' pipelines in which the RM retrieves passages that are included in the LM prompt. We propose Demonstrate-Search-Predict (DSP), a framework that relies on passing natural language texts in sophisticated pipelines between an LM and an RM.",
        "authors": ["Omar Khattab", "Keshav Santhanam", "Xiang Lisa Li", "David Hall", "Percy Liang", "Christopher Potts", "Matei Zaharia"],
        "categories": ["cs.CL"],
        "published": "2022-12-28",
        "updated": "2023-01-26",
        "pdf_url": "https://arxiv.org/pdf/2301.13379",
        "primary_category": "cs.CL",
        "pdf_path": None,
    },
    {
        "arxiv_id": "2303.08774",
        "title": "GPT-4 Technical Report",
        "abstract": "We report the development of GPT-4, a large-scale, multimodal model which can accept image and text inputs and produce text outputs. While less capable than humans in many real-world scenarios, GPT-4 exhibits human-level performance on various professional and academic benchmarks, including passing a simulated bar exam with a score around the top 10% of test takers.",
        "authors": ["OpenAI"],
        "categories": ["cs.CL", "cs.AI"],
        "published": "2023-03-15",
        "updated": "2024-03-04",
        "pdf_url": "https://arxiv.org/pdf/2303.08774",
        "primary_category": "cs.CL",
        "pdf_path": None,
    },
    {
        "arxiv_id": "2307.09288",
        "title": "Llama 2: Open Foundation and Fine-Tuned Chat Models",
        "abstract": "We develop and release Llama 2, a collection of pretrained and fine-tuned large language models (LLMs) ranging in scale from 7 billion to 70 billion parameters. Our fine-tuned LLMs, called Llama 2-Chat, are optimized for dialogue use cases. Our models outperform open-source chat models on most benchmarks we tested, and based on our human evaluations for helpfulness and safety, may be a suitable substitute for closed-source models.",
        "authors": ["Hugo Touvron", "Louis Martin", "Kevin Stone", "Peter Albert", "Amjad Almahairi", "Yasmine Babaei", "Nikolay Bashlykov", "Soumya Batra", "Prajjwal Bhargava", "Shruti Bhosale"],
        "categories": ["cs.CL"],
        "published": "2023-07-18",
        "updated": "2023-07-19",
        "pdf_url": "https://arxiv.org/pdf/2307.09288",
        "primary_category": "cs.CL",
        "pdf_path": None,
    },
    {
        "arxiv_id": "2310.06825",
        "title": "Mistral 7B",
        "abstract": "We introduce Mistral 7B, a 7–billion-parameter language model engineered for superior performance and efficiency. Mistral 7B outperforms the best open 13B model (Llama 2) across all evaluated benchmarks, and the best released 34B model (Llama 1 34B) in reasoning, mathematics, and code generation. Our model leverages grouped-query attention (GQA) for faster inference, coupled with sliding window attention (SWA) to effectively handle sequences of arbitrary length with a reduced inference cost.",
        "authors": ["Albert Q. Jiang", "Alexandre Sablayrolles", "Arthur Mensch", "Chris Bamford", "Devendra Singh Chaplot", "Diego de las Casas", "Florian Bressand", "Gianna Lengyel", "Guillaume Lample", "Lucile Saulnier", "Lélio Renard Lavaud", "Marie-Anne Lachaux", "Pierre Stock", "Teven Le Scao", "Thibaut Lavril", "Thomas Wang", "Timothée Lacroix", "William El Sayed"],
        "categories": ["cs.CL"],
        "published": "2023-10-10",
        "updated": "2023-10-10",
        "pdf_url": "https://arxiv.org/pdf/2310.06825",
        "primary_category": "cs.CL",
        "pdf_path": None,
    },
    {
        "arxiv_id": "2312.11805",
        "title": "Mixtral of Experts",
        "abstract": "We introduce Mixtral 8x7B, a Sparse Mixture of Experts (SMoE) language model. Mixtral has the same architecture as Mistral 7B, with the difference that each layer is composed of 8 feedforward blocks (i.e. experts). For every token, at each layer, a router network selects two experts to process the current state and combine their outputs. Mixtral clearly outperforms Llama 2 70B on most benchmarks with 6x faster inference.",
        "authors": ["Albert Q. Jiang", "Alexandre Sablayrolles", "Antoine Roux", "Arthur Mensch", "Blanche Savary", "Chris Bamford", "Devendra Singh Chaplot", "Diego de las Casas", "Emma Braz Fernandes", "Florian Bressand", "Gianna Lengyel", "Guillaume Bour", "Guillaume Lample", "Lélio Renard Lavaud", "Lucile Saulnier", "Marie-Anne Lachaux", "Pierre Stock", "Sandeep Subramanian", "Sophia Yang", "Szymon Antoniak", "Teven Le Scao", "Théophile Gervet", "Thibaut Lavril", "Thomas Wang", "Timothée Lacroix", "William El Sayed"],
        "categories": ["cs.LG", "cs.CL"],
        "published": "2024-01-08",
        "updated": "2024-01-08",
        "pdf_url": "https://arxiv.org/pdf/2312.11805",
        "primary_category": "cs.LG",
        "pdf_path": None,
    },
    {
        "arxiv_id": "2402.13116",
        "title": "A Survey on Large Language Model-based Autonomous Agents",
        "abstract": "Large language models (LLMs) have demonstrated remarkable capabilities in reasoning, planning, and acting, making them a promising foundation for building autonomous agents. This paper surveys recent progress in LLM-based autonomous agents and presents a comprehensive review of their design principles, architectural components, and applications. We categorize agent systems into single-agent and multi-agent frameworks and discuss key challenges including memory management, planning, and safety.",
        "authors": ["Lei Wang", "Chen Ma", "Xueyang Feng", "Zeyu Zhang", "Hao Yang", "Jingsen Zhang", "Zhiyuan Chen", "Jiakai Tang", "Xu Chen", "Yankai Lin", "Wayne Xin Zhao", "Zhewei Wei", "Ji-Rong Wen"],
        "categories": ["cs.AI", "cs.CL"],
        "published": "2024-02-20",
        "updated": "2024-03-15",
        "pdf_url": "https://arxiv.org/pdf/2402.13116",
        "primary_category": "cs.AI",
        "pdf_path": None,
    },
    {
        "arxiv_id": "2405.16533",
        "title": "AGENTBOARD: An Analytical Evaluation Board of Multi-turn LLM Agents",
        "abstract": "Rigorous evaluation of LLM agents is challenging due to the complex multi-turn nature of agent interactions. We present AGENTBOARD, an analytical evaluation framework for multi-turn LLM agents that provides fine-grained evaluation metrics and tools for understanding agent behavior. AGENTBOARD supports evaluation across multiple task types and provides interpretable metrics at each decision step.",
        "authors": ["Chang Ma", "Junlei Zhang", "Zhihao Zhu", "Cheng Yang", "Yujiu Yang", "Yaohui Jin", "Zhenzhong Lan", "Lingpeng Kong", "Junxian He"],
        "categories": ["cs.AI", "cs.CL"],
        "published": "2024-05-26",
        "updated": "2024-05-26",
        "pdf_url": "https://arxiv.org/pdf/2405.16533",
        "primary_category": "cs.AI",
        "pdf_path": None,
    },
    {
        "arxiv_id": "2405.14751",
        "title": "AgentGym: Evolving Large Language Model-based Agents across Diverse Environments",
        "abstract": "Building generalist agents that can handle diverse tasks and environments is a long-standing goal in artificial intelligence. Large language models (LLMs) show promise as a backbone for such agents due to their extensive knowledge and capabilities. We present AgentGym, a new framework featuring a variety of environments and tasks for developing generalist LLM-based agents. AgentGym includes a platform with diverse interactive environments, an expansive instruction dataset, and a benchmark with in-situ evaluation.",
        "authors": ["Zhiheng Xi", "Yiwen Ding", "Wenxiang Chen", "Boyang Hong", "Honglin Guo", "Junzhe Wang", "Dingwen Yang", "Chenyang Liao", "Xin Guo", "Wei He", "Songyang Gao", "Lu Chen", "Rui Zheng", "Yicheng Zou", "Tao Gui", "Qi Zhang", "Xipeng Qiu", "Xuanjing Huang", "Zuxuan Wu", "Yu-Gang Jiang"],
        "categories": ["cs.AI", "cs.CL"],
        "published": "2024-06-03",
        "updated": "2024-06-03",
        "pdf_url": "https://arxiv.org/pdf/2405.14751",
        "primary_category": "cs.AI",
        "pdf_path": None,
    },
    {
        "arxiv_id": "2406.13537",
        "title": "Towards a Unified View of Preference Learning for Large Language Models: A Survey",
        "abstract": "Large language models (LLMs) have shown remarkable capabilities across various domains. A crucial aspect of making LLMs useful for practical applications is aligning them with human preferences. This paper provides a comprehensive survey of preference learning methods for LLMs, covering reinforcement learning from human feedback (RLHF), direct preference optimization (DPO), and related approaches. We systematically compare different methods and discuss their theoretical foundations.",
        "authors": ["Bofei Gao", "Feifan Song", "Zhe Yang", "Zefeng Cai", "Yibo Miao", "Yixin Nie", "Baobao Chang", "Fei Huang", "Liang Huang", "Tianyu Liu", "Zhifang Sui", "Wenhao Huang", "Yu Li", "Ge Zhang"],
        "categories": ["cs.CL", "cs.AI"],
        "published": "2024-06-19",
        "updated": "2024-06-19",
        "pdf_url": "https://arxiv.org/pdf/2406.13537",
        "primary_category": "cs.CL",
        "pdf_path": None,
    },
    {
        "arxiv_id": "2305.18290",
        "title": "Skeleton-of-Thought: Prompting LLMs for Efficient Parallel Generation",
        "abstract": "This work aims at reducing the end-to-end generation latency of large language models (LLMs). Inspired by how humans often first think out a sketch of the answer and then fill in the details, we propose 'Skeleton-of-Thought' (SoT). SoT first guides the LLM to generate a skeleton of the answer, and then conducts parallel API calls or batched decoding to complete each skeleton point in parallel.",
        "authors": ["Xuefei Ning", "Zinan Lin", "Zixuan Zhou", "Zifu Wang", "Huazhong Yang", "Yu Wang"],
        "categories": ["cs.CL", "cs.AI"],
        "published": "2023-07-23",
        "updated": "2024-02-09",
        "pdf_url": "https://arxiv.org/pdf/2305.18290",
        "primary_category": "cs.CL",
        "pdf_path": None,
    },
    {
        "arxiv_id": "2407.01502",
        "title": "CACTUS: Chemistry Agent Connecting Tool-Use to Science",
        "abstract": "We present CACTUS (Chemistry Agent Connecting Tool-Use to Science), a chemistry-focused LLM agent that integrates multiple chemistry tools and databases to answer complex scientific questions. CACTUS demonstrates how domain-specific tool integration with LLM agents enables expert-level reasoning in specialized domains. The agent architecture includes a planner, tool selector, and synthesizer components.",
        "authors": ["Matthew Tynes", "Wibe A. de Jong", "Daniel T. Mukasa", "Anshumali Shrivastava", "Anatole von Lilienfeld", "Logan Ward", "Henry W. Gabb"],
        "categories": ["cs.AI", "q-bio.QM"],
        "published": "2024-07-02",
        "updated": "2024-07-02",
        "pdf_url": "https://arxiv.org/pdf/2407.01502",
        "primary_category": "cs.AI",
        "pdf_path": None,
    },
    {
        "arxiv_id": "2310.03710",
        "title": "OpenAgents: An Open Platform for Language Agents in the Wild",
        "abstract": "Language agents show potential in being able to utilize natural language to perform complex real-world tasks. Despite this, there are few open platforms available for language agents that support both natural language (conversational) and formal (programming) interfaces, and that are also user-friendly to non-experts while offering rich tooling to experts. We present OpenAgents, an open platform for using and hosting language agents in the wild of everyday life.",
        "authors": ["Tianbao Xie", "Fan Zhou", "Zhoujun Cheng", "Peng Shi", "Luoxuan Weng", "Yitao Liu", "Toh Jing Hua", "Junning Zhao", "Qian Liu", "Che Liu", "Leo Z. Liu", "Yiheng Xu", "Hongjin Su", "Dongchan Shin", "Caiming Xiong", "Tao Yu"],
        "categories": ["cs.AI", "cs.CL"],
        "published": "2023-10-06",
        "updated": "2023-10-17",
        "pdf_url": "https://arxiv.org/pdf/2310.03710",
        "primary_category": "cs.AI",
        "pdf_path": None,
    },
    {
        "arxiv_id": "2404.11483",
        "title": "A Survey on LLM-Based Multi-Agent Systems: Recent Advances and New Frontiers",
        "abstract": "With the development of large language models (LLMs) and the expansion of their application scenarios, LLM-based multi-agent systems (MAS) have shown great potential in solving complex problems. This survey provides a comprehensive overview of recent advances and new frontiers in LLM-based MAS. We discuss the architecture, communication, coordination, and learning strategies in MAS, and survey applications across software engineering, scientific discovery, gaming, and social simulation.",
        "authors": ["Yulong Hou", "Jinghan Li", "Gaole He", "Xiaohan Lu", "Xin Luo", "Wenjun Zhang"],
        "categories": ["cs.AI", "cs.MA"],
        "published": "2024-04-17",
        "updated": "2024-04-17",
        "pdf_url": "https://arxiv.org/pdf/2404.11483",
        "primary_category": "cs.AI",
        "pdf_path": None,
    },
    {
        "arxiv_id": "2212.14024",
        "title": "REPLUG: Retrieval-Augmented Black-Box Language Models",
        "abstract": "We introduce REPLUG (Retrieve and Plug), a retrieval-augmented language modeling framework that treats the language model (LM) as a black box and augments it with a trainable retrieval model. REPLUG prepends retrieved documents to the input to the frozen LM, and uses the LM to supervise the retrieval model. Our key insight is that an LM can directly provide feedback about whether a retrieved document is relevant for a given input.",
        "authors": ["Weijia Shi", "Sewon Min", "Michihiro Yasunaga", "Minjoon Seo", "Rich James", "Mike Lewis", "Luke Zettlemoyer", "Wen-tau Yih"],
        "categories": ["cs.CL"],
        "published": "2022-12-28",
        "updated": "2023-12-29",
        "pdf_url": "https://arxiv.org/pdf/2212.14024",
        "primary_category": "cs.CL",
        "pdf_path": None,
    },
    {
        "arxiv_id": "2305.20050",
        "title": "Large Language Models as Tool Makers",
        "abstract": "Recent research has demonstrated the potential of large language models (LLMs) as general-purpose reasoners that can create and use a wide variety of tools. We propose a closed-loop framework, referred to as LATM (LLMs As Tool Makers), where LLMs create reusable tools for problem-solving. The closed loop consists of two processes: a tool maker and a tool user. The tool maker generates tools while the tool user applies tools to complete tasks.",
        "authors": ["Tianle Cai", "Xuezhi Wang", "Tengyu Ma", "Xinyun Chen", "Denny Zhou"],
        "categories": ["cs.CL", "cs.AI"],
        "published": "2023-05-26",
        "updated": "2023-05-26",
        "pdf_url": "https://arxiv.org/pdf/2305.20050",
        "primary_category": "cs.CL",
        "pdf_path": None,
    },
    {
        "arxiv_id": "2403.04746",
        "title": "AgentOhana: Design Unified Data and Training Pipeline for Effective Agent Learning",
        "abstract": "We introduce AgentOhana, a comprehensive framework for curating and training agent-instruction data for large language models. We present a unified data curation pipeline that aggregates and processes agent-relevant data from diverse sources, including code execution, tool use, web navigation, and API interactions. Our trained models demonstrate strong performance on agentic tasks.",
        "authors": ["Jianguo Zhang", "Tian Lan", "Rithesh Murthy", "Zhiwei Liu", "Weiran Yao", "Juntao Tan", "Thai Hoang", "Liangwei Yang", "Yihao Feng", "Zuxin Liu", "Tulika Awalgaonkar", "Juan Carlos Niebles", "Shelby Heinecke", "Huan Wang", "Silvio Savarese", "Caiming Xiong"],
        "categories": ["cs.AI", "cs.CL"],
        "published": "2024-03-07",
        "updated": "2024-03-07",
        "pdf_url": "https://arxiv.org/pdf/2403.04746",
        "primary_category": "cs.AI",
        "pdf_path": None,
    },
    {
        "arxiv_id": "2310.06117",
        "title": "AdaPlanner: Adaptive Planning from Feedback with Language Models",
        "abstract": "Large language models (LLMs) have recently demonstrated the ability to plan and act in response to environmental feedback. However, most existing approaches either re-plan from scratch when facing failures, or only do minor plan edits. We propose AdaPlanner, an LLM-based closed-loop planning approach with adaptive plan refinement. AdaPlanner allows the LLM agent to refine the plan both in-plan and out-of-plan, in response to environmental feedback.",
        "authors": ["Haotian Sun", "Yuchen Zhuang", "Lingkai Kong", "Bo Dai", "Chao Zhang"],
        "categories": ["cs.AI", "cs.CL"],
        "published": "2023-10-09",
        "updated": "2023-12-01",
        "pdf_url": "https://arxiv.org/pdf/2310.06117",
        "primary_category": "cs.AI",
        "pdf_path": None,
    },
    {
        "arxiv_id": "2402.01680",
        "title": "AgentCoder: Multi-Agent Code Generation with User Feedback",
        "abstract": "Large language models (LLMs) have shown remarkable capabilities for code generation. However, single LLM approaches often struggle with complex programming tasks. We propose AgentCoder, a multi-agent code generation framework with a programmer agent and a test designer agent that collaborate to solve complex coding tasks. The programmer agent generates code while the test designer creates test cases that validate correctness.",
        "authors": ["Dong Huang", "Qingwen Bu", "Jie M. Zhang", "Michael Luck", "Heming Cui"],
        "categories": ["cs.SE", "cs.AI"],
        "published": "2023-12-19",
        "updated": "2024-01-26",
        "pdf_url": "https://arxiv.org/pdf/2402.01680",
        "primary_category": "cs.SE",
        "pdf_path": None,
    },
    {
        "arxiv_id": "2405.01513",
        "title": "Llama 3: Open Foundation Models",
        "abstract": "Meta developed and released the Llama 3 family of large language models (LLMs), a collection of pretrained and instruction tuned generative text models in 8B and 70B sizes. The Llama 3 instruction tuned models are optimized for dialogue use cases and outperform many of the available open source chat models on common industry benchmarks. Further, in developing these models, we took great care to optimize helpfulness and safety.",
        "authors": ["Meta AI"],
        "categories": ["cs.CL", "cs.AI"],
        "published": "2024-07-31",
        "updated": "2024-07-31",
        "pdf_url": "https://arxiv.org/pdf/2405.01513",
        "primary_category": "cs.CL",
        "pdf_path": None,
    },
    {
        "arxiv_id": "2311.12983",
        "title": "AppAgent: Multimodal Agents as Smartphone Users",
        "abstract": "We introduce a novel LLM-based multimodal agent framework designed to operate smartphone applications. Our framework enables the agent to autonomously operate smartphone applications through a simplified action space, mirroring how humans interact with smartphones. The agent uses exploration and learning to understand the functionality of apps without access to the underlying source code.",
        "authors": ["Chi Zhang", "Zhao Yang", "Jiaxuan Liu", "Yucheng Han", "Xin Chen", "Zebiao Huang", "Bin Fu", "Gang Yu"],
        "categories": ["cs.AI", "cs.HC"],
        "published": "2023-12-21",
        "updated": "2024-01-30",
        "pdf_url": "https://arxiv.org/pdf/2311.12983",
        "primary_category": "cs.AI",
        "pdf_path": None,
    },
    {
        "arxiv_id": "2404.07143",
        "title": "ReST-MCTS*: LLM Self-Training via Process Reward Guided Tree Search",
        "abstract": "Recent methodologies in LLM self-training mostly rely on process reward models (PRM) for better step-level guidance. In this paper, we propose ReST-MCTS*, a self-training approach that uses Monte Carlo Tree Search (MCTS) guided by a learned process reward model. Our approach iteratively generates high-quality reasoning paths through MCTS and uses them to train a new PRM and policy model.",
        "authors": ["Dan Zhang", "Sining Zhoubian", "Yisong Yue", "Yuxiao Dong", "Jie Tang"],
        "categories": ["cs.CL", "cs.AI"],
        "published": "2024-06-14",
        "updated": "2024-06-14",
        "pdf_url": "https://arxiv.org/pdf/2404.07143",
        "primary_category": "cs.CL",
        "pdf_path": None,
    },
    {
        "arxiv_id": "2408.02479",
        "title": "SciAgent: Tool-augmented Language Models for Scientific Reasoning",
        "abstract": "Scientific reasoning requires integrating knowledge from multiple sources and applying diverse analytical tools. We present SciAgent, a tool-augmented language model framework for scientific question answering. SciAgent equips LLMs with a suite of scientific tools including computational notebooks, knowledge bases, and specialized calculators. We evaluate SciAgent on a new scientific reasoning benchmark and demonstrate significant improvements over baseline LLMs.",
        "authors": ["Yubo Ma", "Zhibin Gou", "Junheng Hao", "Ruochen Xu", "Shiwei Wu", "Zhiyong Wu", "Ji-Rong Wen", "Edward Y. Chang"],
        "categories": ["cs.AI", "cs.CL"],
        "published": "2024-08-05",
        "updated": "2024-08-05",
        "pdf_url": "https://arxiv.org/pdf/2408.02479",
        "primary_category": "cs.AI",
        "pdf_path": None,
    },
    {
        "arxiv_id": "2310.01558",
        "title": "Self-Knowledge Guided Retrieval Augmentation for Large Language Models",
        "abstract": "Large language models (LLMs) often struggle to recognize the boundaries of their own knowledge, leading to hallucinations when answering questions outside their training distribution. We propose SKR (Self-Knowledge Guided Retrieval), a method that allows LLMs to gauge their own knowledge on a query and decide whether to retrieve external information. By categorizing questions into known and unknown knowledge, we reduce unnecessary retrievals while improving accuracy.",
        "authors": ["Yile Wang", "Peng Li", "Maosong Sun", "Yang Liu"],
        "categories": ["cs.CL"],
        "published": "2023-10-02",
        "updated": "2023-10-02",
        "pdf_url": "https://arxiv.org/pdf/2310.01558",
        "primary_category": "cs.CL",
        "pdf_path": None,
    },
    {
        "arxiv_id": "2308.00352",
        "title": "ProAgent: Building Proactive Cooperative Agents with Large Language Models",
        "abstract": "Building agents that can proactively assist humans requires the agent to be able to anticipate human needs and take initiative. We introduce ProAgent, an LLM-based agent that can proactively cooperate with human in embodied tasks. ProAgent models the human's task status and mind state, and leverages them to anticipate what assistance is needed and provide proactive help.",
        "authors": ["Ceyao Zhang", "Kaixin Yang", "Guowei Hu", "Zhaowei Zhang", "Zhiyuan Liu", "Maosong Sun"],
        "categories": ["cs.AI", "cs.HC"],
        "published": "2023-08-01",
        "updated": "2023-08-01",
        "pdf_url": "https://arxiv.org/pdf/2308.00352",
        "primary_category": "cs.AI",
        "pdf_path": None,
    },
    {
        "arxiv_id": "2401.04088",
        "title": "ToolChain*: Efficient Action Space Navigation in Large Language Models with A* Search",
        "abstract": "Large language models (LLMs) have shown great potential as autonomous agents to tackle complex tasks in real-world scenarios. However, reasoning through a complex problem often requires multi-step planning with tools, which is still challenging for LLMs due to the vast and discretized action space. We propose ToolChain*, a novel LLM-based agent planning algorithm that formulates the agent decision-making process as a tree search problem and employs an A* search algorithm.",
        "authors": ["Yuchen Zhuang", "Xiang Chen", "Tong Yu", "Saayan Mitra", "Victor Bursztyn", "Ryan A. Rossi", "Somdeb Sarkhel", "Chao Zhang"],
        "categories": ["cs.AI", "cs.CL"],
        "published": "2023-10-10",
        "updated": "2024-01-30",
        "pdf_url": "https://arxiv.org/pdf/2401.04088",
        "primary_category": "cs.AI",
        "pdf_path": None,
    },
]

if __name__ == "__main__":
    out = PROCESSED_DIR / "papers_metadata.json"
    with open(out, "w", encoding="utf-8") as f:
        json.dump(PAPERS, f, indent=2, ensure_ascii=False)
    print(f"Saved {len(PAPERS)} papers to {out}")
    for p in PAPERS:
        print(f"  {p['arxiv_id']} — {p['title'][:70]}")
